"""Patch demo_setup.ipynb: append AD-SFL markdown + code cells at the end."""
import json, uuid

NB_PATH = r"c:\Users\Tomal\Desktop\my-projects\ad-sfl\demo_setup.ipynb"

# ------------------------------------------------------------------
# Markdown cell
# ------------------------------------------------------------------
md_source = [
    "### Step 5: AD-SFL Simulation\n",
    "\n",
    "AD-SFL (Anomaly-Detection Split Federated Learning) detects malicious clients each round using KL-divergence anomaly scores, a Fisher-based dynamic tau threshold, and a DDPG agent that learns the per-round acceptance threshold omega.  \n",
    "Attacks are pre-applied to client data loaders (already done in Step 2) — no extra setup needed here.\n",
    "\n",
    "**Key configurable options (in `AdSflConfig`):**\n",
    "- `kl_estimator = \"binning\"` or `\"kde\"` — anomaly scoring method  \n",
    "- `use_static_tau = False` — Fisher-based dynamic tau (set `True` + `static_tau_value` for a fixed threshold)  \n",
    "- `rl_*` knobs — DDPG learning-rate, memory size, noise, omega bounds, etc."
]

md_cell = {
    "cell_type": "markdown",
    "metadata": {},
    "source": md_source
}

# ------------------------------------------------------------------
# Code cell
# ------------------------------------------------------------------
code_source = [
    "import copy\n",
    "import matplotlib.pyplot as plt\n",
    "from tqdm.auto import trange\n",
    "from torch.utils.data import DataLoader\n",
    "\n",
    "from src.algorithms import (\n",
    "    run_ad_sfl_round,\n",
    "    AdSflConfig,\n",
    "    AdSflState,\n",
    "    sample_reference_data_per_label,\n",
    ")\n",
    "from src.algorithms.evaluate import (\n",
    "    evaluate_backdoor_asr,\n",
    "    evaluate_targeted_asr,\n",
    "    evaluate_pair_flip_asr,\n",
    ")\n",
    "\n",
    "# ── AD-SFL hyper-parameters ────────────────────────────────────────\n",
    "ADSFL_KL_ESTIMATOR = 'binning'   # 'binning' or 'kde'\n",
    "ADSFL_ROUNDS       = 50\n",
    "ADSFL_LOCAL_EPOCHS = 1\n",
    "\n",
    "# ── Re-initialise models & clients (fresh weights) ─────────────────\n",
    "print('Re-initializing models for AD-SFL...')\n",
    "base_client_model, server_model = get_split_models(DATASET, weights=PRETRAINED_WEIGHTS)\n",
    "server = SplitFedServer(\n",
    "    model=server_model, num_clients=num_clients,\n",
    "    lr=learning_rate, device=device\n",
    ")\n",
    "clients = []\n",
    "for i in range(num_clients):\n",
    "    client_model = copy.deepcopy(base_client_model)\n",
    "    is_mal = i in malicious_clients_indices\n",
    "    c_dataset = client_datasets[i]\n",
    "    if is_mal and ATTACK_TYPE != 'none':\n",
    "        c_dataset = PoisonedDataset(\n",
    "            c_dataset, attack_type=ATTACK_TYPE,\n",
    "            attack_kwargs=ATTACK_KWARGS,\n",
    "            dataset_name=DATASET, seed=GLOBAL_SEED + i\n",
    "        )\n",
    "    client = SplitFedClient(\n",
    "        client_id=i, model=client_model, dataset=c_dataset,\n",
    "        batch_size=batch_size, lr=learning_rate,\n",
    "        device=device, is_malicious=is_mal\n",
    "    )\n",
    "    clients.append(client)\n",
    "\n",
    "# ── Config & persistent state ───────────────────────────────────────\n",
    "num_classes = 100 if DATASET == 'CIFAR100' else 10\n",
    "adsfl_cfg = AdSflConfig(\n",
    "    kl_estimator=ADSFL_KL_ESTIMATOR,\n",
    "    num_classes=num_classes,\n",
    ")\n",
    "adsfl_state = AdSflState(\n",
    "    num_clients=num_clients,\n",
    "    cfg=adsfl_cfg,\n",
    "    device=str(device),\n",
    ")\n",
    "\n",
    "# ── Test loader ─────────────────────────────────────────────────────\n",
    "test_loader = DataLoader(\n",
    "    test_data, batch_size=batch_size,\n",
    "    shuffle=False, num_workers=4, pin_memory=True\n",
    ")\n",
    "\n",
    "# ── Reference data (sampled once, refreshed inside each round) ──────\n",
    "ref_samples = sample_reference_data_per_label(\n",
    "    train_data,\n",
    "    num_samples_per_label=adsfl_cfg.num_samples_per_label,\n",
    "    num_classes=num_classes,\n",
    "    device=str(device),\n",
    ")\n",
    "\n",
    "# ── History buffers ──────────────────────────────────────────────────\n",
    "adsfl_test_acc  = []\n",
    "adsfl_asr       = []\n",
    "adsfl_tau       = []\n",
    "adsfl_omega     = []\n",
    "adsfl_accepted  = []\n",
    "\n",
    "malicious_indices_list = list(malicious_clients_indices)\n",
    "\n",
    "# ── Training loop ────────────────────────────────────────────────────\n",
    "pbar = trange(ADSFL_ROUNDS, desc='AD-SFL', unit='round')\n",
    "for rnd in pbar:\n",
    "    result = run_ad_sfl_round(\n",
    "        clients=clients,\n",
    "        server=server,\n",
    "        state=adsfl_state,\n",
    "        ref_samples=ref_samples,\n",
    "        test_loader=test_loader,\n",
    "        malicious_indices=malicious_indices_list,\n",
    "        rnd=rnd,\n",
    "        total_rounds=ADSFL_ROUNDS,\n",
    "        cfg=adsfl_cfg,\n",
    "        device=str(device),\n",
    "        local_epochs=ADSFL_LOCAL_EPOCHS,\n",
    "    )\n",
    "\n",
    "    test_acc = result['test_acc']\n",
    "    adsfl_test_acc.append(test_acc)\n",
    "    adsfl_tau.append(result['tau'])\n",
    "    adsfl_omega.append(result['omega'])\n",
    "    adsfl_accepted.append(len(result['accepted_clients']))\n",
    "\n",
    "    # ── ASR evaluation ───────────────────────────────────────────────\n",
    "    accepted_ids = result['accepted_clients']\n",
    "    eval_client  = clients[accepted_ids[0]].model if accepted_ids else clients[0].model\n",
    "    asr = 0.0\n",
    "    if ATTACK_TYPE == 'backdoor':\n",
    "        asr = evaluate_backdoor_asr(\n",
    "            eval_client, server.model, test_loader,\n",
    "            ATTACK_KWARGS.get('backdoor_source_labels', []),\n",
    "            ATTACK_KWARGS.get('backdoor_target_label', 0),\n",
    "            ATTACK_KWARGS, device\n",
    "        )\n",
    "    elif ATTACK_TYPE == 'targeted':\n",
    "        asr = evaluate_targeted_asr(\n",
    "            eval_client, server.model, test_loader,\n",
    "            ATTACK_KWARGS.get('targeted_source_labels', []),\n",
    "            ATTACK_KWARGS.get('targeted_target_label', 0),\n",
    "            device\n",
    "        )\n",
    "    elif ATTACK_TYPE == 'pair_flip':\n",
    "        asr = evaluate_pair_flip_asr(\n",
    "            eval_client, server.model, test_loader,\n",
    "            ATTACK_KWARGS.get('label_pairs_to_flip', []),\n",
    "            device\n",
    "        )\n",
    "    adsfl_asr.append(asr)\n",
    "\n",
    "    pbar.set_postfix(\n",
    "        acc=f'{test_acc:.3f}', asr=f'{asr:.3f}',\n",
    "        tau=f'{result[\"tau\"]:.3f}', omega=f'{result[\"omega\"]:.3f}',\n",
    "        accepted=f'{len(accepted_ids)}/{num_clients}'\n",
    "    )\n",
    "\n",
    "print('AD-SFL training complete.')\n",
    "\n",
    "# ── Plotting ─────────────────────────────────────────────────────────\n",
    "rounds_axis = range(1, ADSFL_ROUNDS + 1)\n",
    "\n",
    "fig, axes = plt.subplots(2, 2, figsize=(14, 8))\n",
    "fig.suptitle(f'AD-SFL ({ADSFL_KL_ESTIMATOR}) — {ATTACK_TYPE} attack, '\n",
    "             f'malicious fraction={MALICIOUS_FRACTION}')\n",
    "\n",
    "# Test accuracy & ASR\n",
    "ax = axes[0, 0]\n",
    "ax.plot(rounds_axis, adsfl_test_acc, marker='o', markersize=3, label='Test Accuracy')\n",
    "ax.plot(rounds_axis, adsfl_asr,      marker='x', markersize=3, label='ASR')\n",
    "ax.set_title('Accuracy & ASR'); ax.set_xlabel('Round'); ax.legend(); ax.grid(True)\n",
    "\n",
    "# Dynamic tau\n",
    "ax = axes[0, 1]\n",
    "ax.plot(rounds_axis, adsfl_tau, marker='o', markersize=3, color='orange', label='tau (Fisher)')\n",
    "ax.set_title('Fisher Tau'); ax.set_xlabel('Round'); ax.legend(); ax.grid(True)\n",
    "\n",
    "# DDPG omega\n",
    "ax = axes[1, 0]\n",
    "ax.plot(rounds_axis, adsfl_omega, marker='o', markersize=3, color='green', label='omega (DDPG)')\n",
    "ax.set_title('DDPG Omega'); ax.set_xlabel('Round'); ax.legend(); ax.grid(True)\n",
    "\n",
    "# Accepted clients per round\n",
    "ax = axes[1, 1]\n",
    "ax.plot(rounds_axis, adsfl_accepted, marker='o', markersize=3, color='purple', label='Accepted clients')\n",
    "ax.axhline(num_clients - len(malicious_clients_indices), color='red', linestyle='--', label='Honest count')\n",
    "ax.set_title('Accepted Clients / Round'); ax.set_xlabel('Round'); ax.legend(); ax.grid(True)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()\n"
]

code_cell = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": code_source
}

# ------------------------------------------------------------------
# Patch notebook
# ------------------------------------------------------------------
with open(NB_PATH, "r", encoding="utf-8") as f:
    nb = json.load(f)

nb["cells"].append(md_cell)
nb["cells"].append(code_cell)

with open(NB_PATH, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f"Notebook now has {len(nb['cells'])} cells.")
print("Done.")
